### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by krtobeabsorbed** [Ragnap/NEU_PC_Emergency#1]
佬，你好，我看您的maven项目中好像缺少了pom文件，我在本地编译的时候servlet文件显示报错，我看好像是依赖的问题，请问您可以发一下pom文件嘛
![Uploading 屏幕截图 2024-06-06 110746.png…]()

**Comment by Ragnap** [comment]
抱歉你的图好像没传上来，但maven的话我只是在报告里提及了但项目里并没有直接使用。如果是缺少servlet-api.jar包导致`src/servlet`下所有的类报错的话应该是tomcat没成功配置导致的。正常来说在tomcat的根目录的lib文件夹下有servlet-api.jar，在运行配置完成后是不需要额外导入这个依赖的。

**Comment by Ragnap** [comment]
我刚刚重新clone下来运行了一下，是能够正常运行的。我把运行配置附加在了项目里，你配好tomcat后试试看能不能正常运行

**Comment by Ragnap** [comment]
抱歉您的图好像没传上来，但maven的话我只是在报告里提及了但项目里并没有直接使用。如果是缺少servlet-api.jar包导致`src/servlet`下所有的类报错的话应该是tomcat没成功配置导致的。正常来说在tomcat的根目录的lib文件夹下有servlet-api.jar，在运行配置完成后是不需要额外导入这个依赖的。
我刚刚重新clone下来运行了一下，是能够正常运行的。我把运行配置附加在了项目里重新上传了一次，您配好tomcat后试试看能不能正常运行

**Comment by krtobeabsorbed** [comment]
嗷嗷，好的，太感谢啦，我重新配置一下
